FROM node:20-alpine
WORKDIR /app
COPY ../frontend/dashboard/package.json .
COPY ../frontend/dashboard/package-lock.json .
RUN npm install
COPY ../frontend/dashboard .
EXPOSE 3000
CMD ["npm", "run", "dev"]
