FROM python:3.11-slim
WORKDIR /app
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ../backend ./backend
COPY ../collectors ./collectors
COPY ../analysis ./analysis
COPY ../database ./database
COPY ../scripts ./scripts
EXPOSE 8000
CMD ["python", "backend/main.py"]
